[CmdletBinding()]
param(
  [string]$RepoRoot = "",
  [string]$OutputPath = "",
  [bool]$IncludeLocalRuntime = $true,
  [string]$CapturedAt = ""
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$skillRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$inspectScript = Join-Path $PSScriptRoot "inspect-environment.ps1"
if ([string]::IsNullOrWhiteSpace($RepoRoot)) {
  $RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $skillRoot "..\.."))
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $OutputPath = Join-Path $skillRoot "references\repo-snapshot.md"
}

$snapshotJson = & $inspectScript `
  -RepoRoot $RepoRoot `
  -IncludeLocalRuntime ([int]$IncludeLocalRuntime) `
  -CapturedAt $CapturedAt |
  Out-String
if ([string]::IsNullOrWhiteSpace($snapshotJson)) {
  throw "Environment inspection returned no JSON."
}
$snapshot = $snapshotJson | ConvertFrom-Json

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Hanako Local Bridge Repository Snapshot")
$lines.Add("")
$lines.Add('> Generated by `scripts/refresh-repo-snapshot.ps1`. Do not place secrets in this file.')
$lines.Add("")
$lines.Add("## Repository")
$lines.Add("")
$lines.Add(('- Captured: `{0}`' -f $snapshot.capturedAt))
$lines.Add(('- Root: `{0}`' -f $snapshot.repository.root))
$lines.Add(('- Remote: `{0}`' -f $snapshot.repository.remote))
$lines.Add(('- Branch: `{0}`' -f $snapshot.repository.branch))
$lines.Add(('- Latest tag: `{0}`' -f $snapshot.repository.latestTag))
$lines.Add("")
$lines.Add(
  'Live commit and dirty state are reported by `scripts/inspect-environment.ps1` and are ' +
  'intentionally not stored in this tracked snapshot.'
)

$lines.Add("")
$lines.Add("## Product")
$lines.Add("")
$lines.Add(('- Rust workspace: `{0}`' -f $snapshot.product.rustVersion))
$lines.Add(('- Stable Node package: `{0}`' -f $snapshot.product.stableVersion))
$lines.Add(('- Signing key present: `{0}`' -f $snapshot.signingKeyPresent))

$lines.Add("")
$lines.Add("## Toolchain")
$lines.Add("")
foreach ($property in $snapshot.tools.PSObject.Properties) {
  $lines.Add(('- {0}: `{1}`' -f $property.Name, $property.Value))
}

$lines.Add("")
$lines.Add("## Latest Local Release Artifacts")
$lines.Add("")
if (@($snapshot.artifacts).Count -eq 0) {
  $lines.Add('No `build\rust-release-*` artifacts found.')
} else {
  $lines.Add("| Name | Bytes | SHA256 |")
  $lines.Add("|---|---:|---|")
  foreach ($artifact in @($snapshot.artifacts)) {
    $lines.Add(('| `{0}` | {1} | `{2}` |' -f
      $artifact.name,
      $artifact.length,
      $artifact.sha256
    ))
  }
}

$lines.Add("")
$lines.Add("## Installed Runtime")
$lines.Add("")
if (-not $snapshot.localRuntime) {
  $lines.Add("Local runtime inspection was disabled.")
} else {
  $runtime = $snapshot.localRuntime
  $lines.Add(('- Install root: `{0}`' -f $runtime.installRoot))
  $lines.Add(('- Installed: `{0}`' -f $runtime.installed))
  $lines.Add(('- Version: `{0}`' -f $runtime.version))
  $lines.Add(('- Health 8787: `{0}`' -f $runtime.health8787))
  $lines.Add(('- Health 8788: `{0}`' -f $runtime.health8788))
  $lines.Add(('- Cloud: `{0}`' -f $runtime.cloudStatus))
  $lines.Add(('- Cloud last error: `{0}`' -f $runtime.cloudLastError))
  $lines.Add(('- Cloud last connected: `{0}`' -f $runtime.cloudLastConnectedAt))
  $lines.Add(('- Cloud last seen: `{0}`' -f $runtime.cloudLastSeenAt))
  $lines.Add(('- Device ID: `{0}`' -f $runtime.deviceId))
  $lines.Add(('- Bridge PID: `{0}`' -f $runtime.bridgePid))
  $lines.Add(('- Main window handle: `{0}`' -f $runtime.mainWindowHandle))
  $lines.Add(('- Manager count: `{0}`' -f $runtime.managerCount))
  $lines.Add(('- Task exists/state: `{0}` / `{1}`' -f
    $runtime.task.exists,
    $runtime.task.state
  ))
  $lines.Add(('- Task last result: `{0}`' -f $runtime.task.lastTaskResult))
  $lines.Add(('- Task hidden: `{0}`' -f $runtime.task.hidden))
  $lines.Add(('- Restart: `{0}` at `{1}`' -f
    $runtime.task.restartCount,
    $runtime.task.restartInterval
  ))
  $lines.Add(('- TimeTrigger/PT1M/IgnoreNew: `{0}` / `{1}` / `{2}`' -f
    $runtime.task.timeTrigger,
    $runtime.task.minuteInterval,
    $runtime.task.ignoreNew
  ))
}

$lines.Add("")
$lines.Add("## Refresh")
$lines.Add("")
$lines.Add("Run from the repository root:")
$lines.Add("")
$lines.Add('```powershell')
$lines.Add('powershell.exe -NoProfile -ExecutionPolicy Bypass -File `')
$lines.Add('  codex-skills\hanako-local-bridge-dev\scripts\refresh-repo-snapshot.ps1 `')
$lines.Add("  -RepoRoot .")
$lines.Add('```')

$outputDirectory = Split-Path -Parent ([System.IO.Path]::GetFullPath($OutputPath))
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
$content = ($lines -join "`n") + "`n"
[System.IO.File]::WriteAllText(
  [System.IO.Path]::GetFullPath($OutputPath),
  $content,
  [System.Text.UTF8Encoding]::new($false)
)

Write-Output ([System.IO.Path]::GetFullPath($OutputPath))
